[env.production]
name = "cloudflare-docker-proxy"
routes = [
   { pattern = "docker.ikankan.eu.org", custom_domain = true },
   { pattern = "quay.ikankan.eu.org", custom_domain = true },
   { pattern = "gcr.ikankan.eu.org", custom_domain = true },
   { pattern = "k8s-gcr.ikankan.eu.org", custom_domain = true },
   { pattern = "k8s.ikankan.eu.org", custom_domain = true },
   { pattern = "ghcr.ikankan.eu.org", custom_domain = true },
   { pattern = "cloudsmith.ikankan.eu.org", custom_domain = true },
 ]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
route = { pattern = "docker-staging.ikankan.eu.org", custom_domain = true }
